# Generated by Django 3.2.5 on 2022-06-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='description_service1',
        ),
    ]
